# Generated by Django 5.2.4 on 2025-09-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='color',
            field=models.CharField(default='#9ef9ff', max_length=6),
        ),
    ]
