# Generated by Django 5.2.4 on 2025-09-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='color',
            field=models.CharField(default='#9ef9ff', max_length=7),
        ),
    ]
