# Generated by Django 5.2.4 on 2025-09-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='type',
            field=models.CharField(choices=[('C', 'Custom'), ('D', 'Default')], default='C'),
        ),
    ]
