# Generated by Django 5.2.4 on 2025-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_genres_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='type',
            field=models.CharField(choices=[('C', 'custom'), ('D', 'default')], default='C'),
        ),
    ]
