# Generated by Django 5.2.4 on 2025-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_genres_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(default='https://cdn.vectorstock.com/i/1000v/52/86/red-cartoon-question-mark-vector-51155286.jpg'),
        ),
    ]
