# Generated by Django 5.2.6 on 2025-09-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_customuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserProfile',
        ),
    ]
